const Dimensions = {
  SCREEN_PADDING: 16,
  SPACE_BETWEEN_SECTIONS: 32,
  LIST_VERTICAL_PADDING: 32,
  BUTTON_RADIUS: 16,
  TITLE_FONT_SIZE: 20,
  ITEM_PADDING: 16,
  ITEM_RADIUS: 16,
  ITEM_TITLE_FONT_SIZE: 16,
  ITEM_CONTENT_FONT_SIZE: 12,
  ITEM_BOTTOM_MARGIN: 10,
  ITEM_HOTIZONTAL_MARGIN: 6,
  SHADOW_OFFSET_WIDTH: 0,
  SHADOW_OFFSET_HEIGHT: 2,
  SHADOW_OPACITY: 0.2,
  SHADOW_RADIUS: 2,
  BUTTON_HORIZONTAL_PADDING: 24,
  BUTTON_VERTICAL_PADDING: 12,
};

export default Dimensions;
